version: '3'
services:
  dclchat:
    env_file:
      .env
    build:
      context: .
    restart: always
    ports:
      - 3000:3000
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dclchat.rule=Host(`chat.dcl.guru`)"
      - "traefik.http.routers.dclchat.entrypoints=https"
      - "traefik.http.routers.dclchat.tls=true"
      - "traefik.http.routers.dclchat.tls.certresolver=http"

networks:
  proxy:
    external: true